import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar.js";
import Footer from "./components/Footer.js"
import Providers from "./Providers";
import SessionWrapper from "./components/SessionWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col bg-stone-800 text-gray-200">

        <Providers>
          <SessionWrapper>


            <Navbar />

            <div className="flex-grow">
              {children}
            </div>

            <Footer />
          </SessionWrapper>
        </Providers>

      </body>
    </html>
  );
}
